version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fakejob
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: fakejob
      JWT_SECRET: change_this_secret
      TYPEORM_SYNC: 'true'
    ports:
      - '3000:3000'

volumes:
  pgdata:
